ALTER TABLE word_bank ADD COLUMN IF NOT EXISTS success_attempts INTEGER DEFAULT 0;
ALTER TABLE word_bank ADD COLUMN IF NOT EXISTS failed_attempts INTEGER DEFAULT 0;
ALTER TABLE word_bank ADD COLUMN IF NOT EXISTS avg_success_attempts DECIMAL(5,3) DEFAULT 0;
ALTER TABLE word_bank ADD COLUMN IF NOT EXISTS last_attempted_at TIMESTAMP DEFAULT NULL;